services:
  api:
    container_name: showcase-api
    build: ./api
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - mysql
      - redis

  simulator:
    container_name: showcase-simulator
    build: ./simulator

  client:
    container_name: showcase-client
    build: ./client
    ports:
      - "127.0.0.1:3000:3000"

  mysql:
    image: mysql:8.0.43
    container_name: showcase-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: showcase
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:18.1-alpine3.23
    container_name: showcase-pg
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8.4-alpine
    container_name: showcase-redis
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  mysql_data:
  pg_data:
